server:
  port: 8083

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_wms
    username: root
    password: 114539

redis:
  host: 196.128.71.129


mybatis-plus:
  mapper-locations: classpath:mapper/wms/**/*.xml
